export type PageKey = 'overview' | 'resources' | 'integrations' | 'catalog' | 'routing' | 'governance' | 'reviews' | 'knowledge' | 'shadow' | 'logs' | 'accounts' | 'snapshots' | 'operations' | 'system'
export type Status = 'active' | 'unknown' | 'meta' | 'stale' | 'retired' | 'disabled'
export interface Model { id: string; provider: string; status: Status; auto_routable: boolean; structured_output: boolean; structured_output_known: boolean; capabilities: string[]; context_window: number; tools: boolean; vision: boolean; capability_evidence?: Record<string, Evidence> }
export interface Evidence { supported: boolean; confidence: number; source: string; level: string; checked_at: string }
export interface Provider { id: string; name?: string; kind: string; models: number; base_url?: string; status?: string; disabled?: boolean; last_sync?: string; cooldown_until?: string; cooldown_active?: boolean; sync_error?: string; sync_error_type?: string; source?: string; read_only?: boolean; enabled?: boolean; api_key_mask?: string; has_api_key?: boolean; verified_at?: string }
export interface ExternalIntegration { id?: string; adapter?: string; endpoint?: string; secret_ref?: string; configured?: boolean; recognized?: boolean; authorized?: boolean; route_enabled?: boolean; connected?: boolean; catalog_fresh?: boolean; usable?: boolean; status?: string; release?: string; model_count?: number; available_models?: number; ready_upstreams?: number; summary_supported?: boolean; last_probe?: string; last_sync?: string; last_quota?: string; last_error?: string; generation?: number; local_quota_state?: string; local_quota_checked_at?: string; local_quota_error?: string; local_quota_stale?: boolean; local_quota_source?: string; local_quota?: LocalQuotaReport }
export interface LocalQuotaModel { platform: string; model_id: string; display_name?: string; enabled: boolean; budget_label?: string; budget_tokens?: number | null; used_tokens: number; remaining_estimate?: number | null; requests: number; input_tokens: number; output_tokens: number; rpm_limit?: number | null; rpd_limit?: number | null; tpm_limit?: number | null; tpd_limit?: number | null; rpm_used?: number; rpd_used?: number; tpm_used?: number; tpd_used?: number; scope: string; source: string }
export interface LocalQuotaTotals { budget_tokens?: number | null; used_tokens: number; remaining_estimate?: number | null; requests: number; input_tokens: number; output_tokens: number }
export interface LocalQuotaReport { schema_version: number; source: string; checked_at: string; month_start: string; totals: LocalQuotaTotals; models: LocalQuotaModel[]; quota_pools: Row[]; partial: boolean; warnings?: string[] }
export type OverviewStatus = 'ready' | 'healthy' | 'unhealthy' | 'unknown'
export interface OverviewHealthProbe { status: OverviewStatus; url?: string; detail?: string }
export interface Overview { health: { service: OverviewHealthProbe; overall: string }; consistency: { catalog: number; governance: number; missing_governance: number; ok: boolean }; providers: Provider[]; recent: { count: number; items: Row[] }; alerts: { count: number; items: Row[] }; generated_at: string }
export type Row = Record<string, unknown>
export interface ReviewerCandidate extends Model { model: string; eligible?: boolean }
export interface ReviewerCandidates { items: ReviewerCandidate[]; probe_candidates: ReviewerCandidate[]; eligible: number; probeable: number; excluded: number; reasons: Record<string, number>; capability_probe_available: boolean }
export interface ProbeBatchStatus { job_id: string; status: 'running' | 'completed' | 'not_found'; total: number; completed: number; failed: number; results?: Row[] }
export interface ProbeBatchHistory { job_id: string; started_at: string; ended_at: string; total: number; completed: number; failed: number; status: string }
export interface Reviewer { model: string; provider: string; consecutive_failures: number; last_error?: string; last_checked_at?: string; selected_at?: string; available?: boolean; state?: string }
export interface ReviewStats { pending: number; processing: number; reviewed: number; failed: number; skipped: number }
export interface Review { id: string; model: string; provider: string; status: number; latency_ms: number; review_status: string; recommended_model?: string; confidence?: number; conclusion?: string; batch_id?: string; review_error?: string; replayable?: boolean; response_captured?: boolean }
export interface ReviewBatch { batch_id: string; total: number; pending: number; processing: number; reviewed: number; failed: number; skipped: number; models: string[]; providers: string[]; last_error?: string }
export interface KnowledgeValidation { id: string; at: string; success: boolean; failure_cause?: string; note?: string; status_from: string; status_to: string }
export interface Knowledge { id: string; signature: string; recommended_model: string; status: string; samples: number; validated_samples: number; successful_samples: number; failed_samples?: number; failure_cause?: string; source_review_ids?: string[]; validation_history?: KnowledgeValidation[]; expires_at?: string; human_note?: string }
export interface Shadow { id?: string; knowledge_id?: string; review_id?: string; batch_id?: string; candidate_model: string; status: string; http_status: number; protocol_ok: boolean; structured_ok: boolean; tool_compatible?: boolean; semantic_match: boolean; success?: boolean; quality_conclusion?: string; failure_cause?: string; error?: string; latency_ms: number }
export interface ShadowBatch { id: string; knowledge_id: string; review_ids: string[]; candidate_model: string; status: string; total: number; completed: number; succeeded: number; failed: number; stopped: number; last_error?: string; created_at: string; updated_at: string }
export type ApiErrorKind = 'timeout' | 'aborted' | 'unauthorized' | 'network' | 'http'
export interface ApiError { message: string; status?: number; kind?: ApiErrorKind; retryable?: boolean; requestId?: string }
